#!/bin/bash
function gen() {
./vt/bin/$1 --help |& tail -n +2 | ruby normalize.rb | sort | ruby make.rb $1
}

bins=($(ls 'vt/bin'))

for bin in "${bins[@]}"; do
  echo "Generating: $bin"
  gen $bin > "diff/$bin.rb"
done
