---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos7
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: ubuntu-1604
    driver_plugin: docker
    driver:
      image: ernestasposkus/ubuntu1604
      run_command: '/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'

suites:
  - name: mysqlctld
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[vitess::mysqlctld]

  - name: vtgate
    run_list:
      - recipe[test-vitess::zookeeper]
      - recipe[vitess::vtgate]

  - name: vttablet
    run_list:
      - recipe[test-vitess::zookeeper]
      - recipe[vitess::vttablet]
