---
settings:
  parallel: false

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos7
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  # TODO
  # - name: ubuntu-1604
  #   driver_plugin: docker
  #   driver:
  #     image: ernestasposkus/ubuntu1604
  #     run_command: '/lib/systemd/systemd'
  #     run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'

topology_attributes_zk2: &topology_attributes_zk2
  vitess: { topo_global_server_address: 'localhost:2181', topo_implementation: 'zk2' }

suites:
  # ETCD topology
  - name: etcd-mysqlctld
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[vitess::mysqlctld]

  - name: etcd-vtgate
    run_list:
      - recipe[test-vitess::etcd]
      - recipe[vitess::vtgate]

  - name: etcd-vttablet
    run_list:
      - recipe[test-vitess::etcd]
      - recipe[vitess::vttablet]

  - name: etcd-vtctld
    run_list:
      - recipe[test-vitess::etcd]
      - recipe[vitess::vtctld]

  - name: etcd-vtworker
    run_list:
      - recipe[test-vitess::etcd]
      - recipe[vitess::vtworker]

  - name: etcd-cluster
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::etcd]
      - recipe[test-vitess::cluster]
    driver:
      forward:
        - '15000:15000'
        - '10000:10000'
        - '10100:10100'
        - '10200:10200'
        - '25000:25000'
        - '25100:25100'
        - '25200:25200'

  - name: etcd-shellwrapper
    run_list:
      - recipe[test-vitess::shell]

  # Zookeeper topology
  - name: zk-mysqlctld
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[vitess::mysqlctld]
    attributes:
      <<: *topology_attributes_zk2

  - name: zk-vtgate
    run_list:
      - recipe[test-vitess::zookeeper]
      - recipe[vitess::vtgate]
    attributes:
      <<: *topology_attributes_zk2

  - name: zk-vttablet
    run_list:
      - recipe[test-vitess::zookeeper]
      - recipe[vitess::vttablet]
    attributes:
      <<: *topology_attributes_zk2

  - name: zk-vtctld
    run_list:
      - recipe[test-vitess::zookeeper]
      - recipe[vitess::vtctld]
    attributes:
      <<: *topology_attributes_zk2

  - name: zk-vtworker
    run_list:
      - recipe[test-vitess::zookeeper]
      - recipe[vitess::vtworker]
    attributes:
      <<: *topology_attributes_zk2

  - name: zk-cluster
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::zookeeper]
      - recipe[test-vitess::cluster]
    attributes:
      <<: *topology_attributes_zk2
    driver:
      forward:
        - '15001:15000'
        - '10001:10000'
        - '10101:10100'
        - '10201:10200'
        - '25001:25000'
        - '25101:25100'
        - '25201:25200'

  - name: zk-shellwrapper
    run_list:
      - recipe[test-vitess::shell]
    attributes:
      <<: *topology_attributes_zk2
