---
settings:
  parallel: false

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'
  require_chef_omnibus: 17
  product_name: cinc

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_plugin: docker
    driver:
      image: centos:7
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: rockylinux-8
    driver_plugin: docker
    driver:
      image: rockylinux:8
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'


topology_attributes_zk2: &topology_attributes_zk2
  vitess: { topo_global_server_address: 'localhost:2181', topo_implementation: 'zk2' }

suites:
  # ETCD topology
  - name: etcd-default
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::etcd]
      - recipe[vitess::mysqlctld]
      - recipe[vitess::vtgate]
      - recipe[vitess::vttablet]
      - recipe[vitess::vtctld]
      - recipe[vitess::vtworker]
    verifier:
      inspec_tests:
        - test/integration/mysqlctld
        - test/integration/vtgate
        - test/integration/vttablet
        - test/integration/vtctld
        - test/integration/vtworker

  - name: etcd-test-cluster
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::etcd]
      - recipe[test-vitess::cluster]
      - recipe[test-vitess::shell]
    verifier:
      inspec_tests:
        - test/integration/etcd
        - test/integration/cluster
        - test/integration/shellwrapper

  - name: etcd-default-vitess-9
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::etcd]
      - recipe[vitess::mysqlctld]
      - recipe[vitess::vtgate]
      - recipe[vitess::vttablet]
      - recipe[vitess::vtctld]
      - recipe[vitess::vtworker]
    verifier:
      inspec_tests:
        - test/integration/mysqlctld
        - test/integration/vtgate
        - test/integration/vttablet
        - test/integration/vtctld
        - test/integration/vtworker
    attributes:
      vitess:
        version:
          mysqlctld: v9.0.2-58cd7b0
          vtctlclient: v9.0.2-58cd7b0
          vtctld: v9.0.2-58cd7b0
          vtgate: v9.0.2-58cd7b0
          vttablet: v9.0.2-58cd7b0
          vtworker: v9.0.2-58cd7b0
          mysqlctl: v9.0.2-58cd7b0
          vtctl: v9.0.2-58cd7b0
          vtexplain: v9.0.2-58cd7b0
          vtbench: v9.0.2-58cd7b0

  - name: etcd-default-vitess-10
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::etcd]
      - recipe[vitess::mysqlctld]
      - recipe[vitess::vtgate]
      - recipe[vitess::vttablet]
      - recipe[vitess::vtctld]
      - recipe[vitess::vtworker]
    verifier:
      inspec_tests:
        - test/integration/mysqlctld
        - test/integration/vtgate
        - test/integration/vttablet
        - test/integration/vtctld
        - test/integration/vtworker
    attributes:
      vitess:
        version:
          mysqlctld: v10.0.2-fc78470
          vtctlclient: v10.0.2-fc78470
          vtctld: v10.0.2-fc78470
          vtgate: v10.0.2-fc78470
          vttablet: v10.0.2-fc78470
          vtworker: v10.0.2-fc78470
          mysqlctl: v10.0.2-fc78470
          vtctl: v10.0.2-fc78470
          vtexplain: v10.0.2-fc78470
          vtbench: v10.0.2-fc78470

  - name: etcd-default-vitess-11
    run_list:
      - recipe[test-vitess::mysql]
      - recipe[test-vitess::etcd]
      - recipe[vitess::mysqlctld]
      - recipe[vitess::vtgate]
      - recipe[vitess::vttablet]
      - recipe[vitess::vtctld]
      - recipe[vitess::vtworker]
    verifier:
      inspec_tests:
        - test/integration/mysqlctld
        - test/integration/vtgate
        - test/integration/vttablet
        - test/integration/vtctld
        - test/integration/vtworker
    attributes:
      vitess:
        version:
          mysqlctld: v11.0.1-92ac1ff
          vtctlclient: v11.0.1-92ac1ff
          vtctld: v11.0.1-92ac1ff
          vtgate: v11.0.1-92ac1ff
          vttablet: v11.0.1-92ac1ff
          vtworker: v11.0.1-92ac1ff
          mysqlctl: v11.0.1-92ac1ff
          vtctl: v11.0.1-92ac1ff
          vtexplain: v11.0.1-92ac1ff
          vtbench: v11.0.1-92ac1ff
