language: ruby
sudo: required

services:
  - docker

rvm:
  - 2.3.1

install: bundle install --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle

script:
  - bundle exec kitchen test --concurrency

notifications:
  disable: true
