default['vitess']['user'] = 'vitess'
default['vitess']['group'] = 'vitess'

default['vitess']['version']['mysqlctld'] = 'v3.0.0'
default['vitess']['version']['vtctlclient'] = 'v3.0.0'
default['vitess']['version']['vtctld'] = 'v3.0.0'
default['vitess']['version']['vtgate'] = 'v3.0.0'
default['vitess']['version']['vttablet'] = 'v3.0.0'
default['vitess']['version']['vtworker'] = 'v3.0.0'
default['vitess']['version']['mysqlctl'] = 'v3.0.0'
